### ISSUE TITLE
Unable to Start Script

### ISSUE THREAD

**Issue by Latiron** [haxcop/AutomatedHMS#1]
The batch file is missing some syntax which is currently causing the process to fail.  It gets hung up with the word You, so there must be a " or } needed or misplaced.

Also, if you just open powershell, and after you have right clicked on the automated.ps1 file and check the box for unblock, you get this error when running the PS file.

PS C:\Users\latiron\Documents\AutomatedHMS-master\IPTV Telly Automation> .\automated.ps1
At C:\Users\latiron\Documents\AutomatedHMS-master\IPTV Telly Automation\automated.ps1:110 char:19
+ Function ADD-PATH {
+                   ~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingEndCurlyBrace

PS C:\Users\latiron\Documents\AutomatedHMS-master\IPTV Telly Automation>

**Comment by haxcop** [comment]
@Latiron Thanks for your time.
Could you please send me your Powershell version?  
`$PSVersionTable`

**Comment by haxcop** [comment]
The problem seems to be with the last windows update that involve the last PS Version 
PS C:\Users\Carlos> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.48
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.48
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
 

But it does works into the previous Versioin
 ----
Working to solve this as soon as possible. Thanks for the patience.

**Comment by haxcop** [comment]
@Latiron Created a second set _v3 that works on any Win10 Version

**Comment by Latiron** [comment]
Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by haxcop** [comment]
@Latiron the issue is solver in the V3 of the script. 
Thanks for reporting.
